### ISSUE TITLE
Detailed steps for installing swix on a new project

### ISSUE THREAD

**Issue by sniis84** [stsievert/swix#24]
Please give a detailed and working steps for installing swix on a new project.
I tried several times to follow the given steps.
First I found that OpenCV must be added as Framework in order to compile the project.
In this way the project compiles but the functions cannot be called in any swift file, how to make swix to work?

Many thanks

**Comment by stsievert** [comment]
I do include some instructions on *[Installation][1]*. Theres no section on integrating with an existing project but I believe following step 4 under *[creating a new project that uses swix][2]* can link to the proper frameworks/etc.

I believe this is related to issue #23, reformatting for use with the Swift package manager -- I believe these compiler-linking parameters are specified in some text file. I'm not currently actively developing this (I'll probably fix #23 over the summer), so please feel free to ask further questions/post screenshots/etc. I'll do my best to answer.

[2]:http://scottsievert.com/swix/installation.html#how-to-creat-a-new-ios-app-that-includes-swix
[1]:http://scottsievert.com/swix/installation.html

**Comment by sniis84** [comment]
Maybe I wasn't clear your instructions does not work.
The tutorial that you give is perfect I can tests everything in it. But I cannot create a new project because the library commands do not work.
I followed ALL the steps and the project does not compile.
You might miss some steps in your instructions. Such as adding OpenCV framework (only one I figured out) and maybe something else.
Adding OpenCV framework I can compile but I cannot call your functions

**Comment by sniis84** [comment]
![swix](https://cloud.githubusercontent.com/assets/9617798/13839302/4c1f4192-ec1a-11e5-88b3-43db214220c6.png)

why my swix folder has a different color respect to the tutorial? Something is missing?

**Comment by stsievert** [comment]
Hm, this sounds like the swix files aren't included in the project -- Xcode doesn't know where to look to find these functions. I'm pretty sure this issue is caused by the process of adding source files to an Xcode project. I normally follow this process: http://stackoverflow.com/a/15195403

**Comment by sniis84** [comment]
I was all Xcode fault! I made a cache cleaning of the system and Xcode folders.
I manage to include your stuff in my custom project! Thanks for the support!!

**Comment by stsievert** [comment]
I'll add a tip to the installation guide to clean the cache. Thanks for testing and using!

**Comment by stsievert** [comment]
To be clear, you selected Product > Clean? That fixed your issue?

**Comment by sniis84** [comment]
Nope. I deleted the 'Derived Data' folder of Xcode in the Library of my user.
Moreover I'd add the following pic to your instructions while you say to include the folder 'swix'.
![unnamed](https://cloud.githubusercontent.com/assets/9617798/13901956/0a4b617e-ee36-11e5-89d3-b1335c6d3d35.png)

Many thanks again for your support and your amazing work.
Please keep it up I'd like to see how is it going to develop.
Just to ask a thing, any change to have multi-dimensional arrays in the near future?

**Comment by stsievert** [comment]
Thanks, I'll revise the swix docs with that picture.

Only 1D and 2D arrays (aka vectors and matrices) are currently supported. This is all I saw the need to develop. The code for 1/2D arrays is pretty stable and I don't plan on changing it anytime soon.

**Comment by stsievert** [comment]
So if you had added swix while checking the "copy items if needed" the issue would have been avoided?

**Comment by sniis84** [comment]
You must have "copy items if needed and "create groups".
In my case, if I don't do this at the first time I had to clean the "DerivedData" Xcode folder in my Library.
That is the main important step for the installation.

**Comment by stsievert** [comment]
Thanks for the clarification.
