### ISSUE TITLE
issue about: linker command failed with exit code 1

### ISSUE THREAD

**Issue by sniis84** [stsievert/swix#25]
Everything works fine on the Simulation, as soon as I plug any device I cannot install the App.
The following error appars.

```
ld: '/mypath/myproject/swix/objc/opencv2.framework/opencv2(knearest.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It seems a `clang` problem any idea how to solve it?

**Comment by stsievert** [comment]
Hm, I don't recall running into this issue. My first move would be to start from a clean slate -- I would delete the app from the device, restart the device, Xcode clean, etc.

**Comment by sniis84** [comment]
I've never achieved to install the App in the device. This is the behavior since the beginning.
I only tested it on the simulators.
I tried on three devices (iPhone, iPad & iPod Touch) always the same error though, Of course I restarted, the Mac, Xcode, cleaned the cache again, but nothing :(

**Comment by sniis84** [comment]
I don't know why this solved the issue but following this link [http://stackoverflow.com/questions/31205133/how-to-enable-bitcode-in-xcode-7](url)
I just disabled Bitcode and now I'm able to install the App on all my devices.
Perhaps you want to add this hint in your documentation.
![schermata 2016-03-21 alle 08 16 26](https://cloud.githubusercontent.com/assets/9617798/13912498/e035c5ce-ef3d-11e5-8105-c31efa9c341f.png)

**Comment by stsievert** [comment]
I've added a link from the documentation to these issues.
