### ISSUE TITLE
The ndarray type is not n-dimensional but 1-dimensional

### ISSUE THREAD

**Issue by Rodmore** [stsievert/swix#27]
Due to this all the ndarray and some of the matrix operations don't have the expected behavior similar to NumPy's.

**Comment by stsievert** [comment]
It can not be n-dimensional; that seemed like too much work. In the field I specialize in, I only see vectors and matrices. In swix, I call these "ndarray" and "matrix" respecively.

Is it easy to covert from an ndarray to a matrix? I forgot the exact interface.

**Comment by stsievert** [comment]
Clarification: I chose "ndarray" because an array with n components is n-dimensional. Maybe a renaming of "ndarray" to "vector" is in order...

**Comment by stsievert** [comment]
I'm reopening this because this naming convention is confusing. I will refactor to address this issue.

**Comment by stsievert** [comment]
I renamed `ndarray` to `vector` with the command `find swix/swix/swix -type f | xargs sed -i ''
's/ndarray/vector/g'`.
