### ISSUE TITLE
Doesn't work with OpenCV 3

### ISSUE THREAD

**Issue by Patrickyp** [stsievert/swix#35]
I followed the directions in your installation instructions and the library seems to be working well with the included OpenCV 2.4.9.  I would like to make it work with OpenCV  3.X.X but when I try to replace the included OpenCV with OpenCV 3 I would get multiple errors:

error core.hpp header must be compiled as C++
error base.hpp header must be compiled as C++

It seems like they added #ifndef __cplusplus in core.hpp that forces C++ in OpenCV 3 

Anyway I can get OpenCV 3 to work with this library?

**Comment by stsievert** [comment]
How are you including OpenCV 3? I believe if you replace the the swix OpenCV framework with the framework found at http://opencv.org/releases.html it *should* work.t

(per title, I seem to remember converting to Swift 3 in #34 though it's documented or clear)
