### ISSUE TITLE
Swift bridging header modification issue

### ISSUE THREAD

**Issue by JimyBasi** [stsievert/swix#36]
Hi
I'm trying to install swix in my IOS app. To do that I follow the different instructions of the swix 0.30 documentation in the "How to creat a new iOS app that includes swix" paragraph.

For me all the different steps are ok until the Swift bridging header modification. As you can see in the attach image, i don't have the objective-c bridging header menu in my project setting.

Have you an idea of my problem?? (for information i used Xcode 8.2.1)

Best regards
![bridging header swift](https://cloud.githubusercontent.com/assets/26691354/24332671/150d0984-124b-11e7-92a7-2ba6250dd782.jpg)

**Comment by stsievert** [comment]
#34 should fix this.

The below SO question has some tips on adding a bridging header. There's some field in the build settings, but the easiest way is to add a `.m` file yourself and click "yes" at the prompt.

https://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift
