### ISSUE TITLE
Add Swix to the Swift Source Compatibility test suite

### ISSUE THREAD

**Issue by felix91gr** [stsievert/swix#37]
[Here](https://swift.org/source-compatibility/#current-list-of-projects) it is.

[These](https://github.com/stsievert/swix/blob/master/swix/swix/swix/tests/tests.swift) tests should be good enough. I think.

#### Edit

Ah, I see. You're working now on the package-manager branch. Take your time... :)
Maybe I'll drop a PR to help you implementing/porting/testing stuff ^^

**Comment by stsievert** [comment]
I would love help with the port/with the package-manager branch. 

Looking at the requirements for inclusion to the Source Compatibility:

> Have maintainers who will commit to resolve issues in a timely manner

I can't commit to this.

**Comment by stsievert** [comment]
The package-manager branch is moving to Swix 3 and refactoring a bit (renaming vector to Vector, etc)

**Comment by stsievert** [comment]
Well, and also moving to the Swift Package Manager.
