### ISSUE TITLE
image classification support

### ISSUE THREAD

**Issue by sandeepkumarrepo** [stsievert/swix#43]
Hi Team,

does this library support the image classification or we can say object detection in image? for example, identifying cat, dog, etc in a image.

I will be working on my research topic where I need this support?

Regards,
Sandeep

**Comment by stsievert** [comment]
This library is no longer actively maintained. I don't know if it even supports modern Swift versions. From the README:

> *Note: [tensorflow/swift][t4sw] and [apple/swift-numerics/issues/6][asn6] have
or will have more complete support for NumPy-like ndarrays and autodiff. Fast AI
has a good overview: https://www.fast.ai/2019/01/10/swift-numerics/*
> 
> *An alternate and much mature library is https://github.com/AlexanderTar/LASwift*

I'm marking this repository as archived.

[t4sw]:https://github.com/tensorflow/swift
[asn6]:https://github.com/apple/swift-numerics/issues/6
